import { ComponentProps } from "react";
import { Drawer as DrawerPrimitive } from "vaul";
declare function Drawer({ ...props }: ComponentProps<typeof DrawerPrimitive.Root>): import("react/jsx-runtime").JSX.Element;
declare function DrawerTrigger({ ...props }: ComponentProps<typeof DrawerPrimitive.Trigger>): import("react/jsx-runtime").JSX.Element;
declare function DrawerPortal({ ...props }: ComponentProps<typeof DrawerPrimitive.Portal>): import("react/jsx-runtime").JSX.Element;
declare function DrawerClose({ ...props }: ComponentProps<typeof DrawerPrimitive.Close>): import("react/jsx-runtime").JSX.Element;
declare function DrawerOverlay({ className, ...props }: ComponentProps<typeof DrawerPrimitive.Overlay>): import("react/jsx-runtime").JSX.Element;
declare function DrawerContent({ className, children, ...props }: ComponentProps<typeof DrawerPrimitive.Content>): import("react/jsx-runtime").JSX.Element;
declare function DrawerHeader({ className, ...props }: ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
declare function DrawerFooter({ className, ...props }: ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
declare function DrawerTitle({ className, ...props }: ComponentProps<typeof DrawerPrimitive.Title>): import("react/jsx-runtime").JSX.Element;
declare function DrawerDescription({ className, ...props }: ComponentProps<typeof DrawerPrimitive.Description>): import("react/jsx-runtime").JSX.Element;
export { Drawer, DrawerPortal, DrawerOverlay, DrawerTrigger, DrawerClose, DrawerContent, DrawerHeader, DrawerFooter, DrawerTitle, DrawerDescription, };
