import { ComponentProps } from "react";
declare function Table({ className, ...props }: ComponentProps<"table">): import("react/jsx-runtime").JSX.Element;
declare function TableHeader({ className, ...props }: ComponentProps<"thead">): import("react/jsx-runtime").JSX.Element;
declare function TableBody({ className, ...props }: ComponentProps<"tbody">): import("react/jsx-runtime").JSX.Element;
declare function TableFooter({ className, ...props }: ComponentProps<"tfoot">): import("react/jsx-runtime").JSX.Element;
declare function TableRow({ className, ...props }: ComponentProps<"tr">): import("react/jsx-runtime").JSX.Element;
declare function TableHead({ className, ...props }: ComponentProps<"th">): import("react/jsx-runtime").JSX.Element;
declare function TableCell({ className, ...props }: ComponentProps<"td">): import("react/jsx-runtime").JSX.Element;
declare function TableCaption({ className, ...props }: ComponentProps<"caption">): import("react/jsx-runtime").JSX.Element;
export { Table, TableHeader, TableBody, TableFooter, TableHead, TableRow, TableCell, TableCaption, };
